name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install build-essential
        wget https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        sudo dkp-pacman -Sy switch-dev --noconfirm
        sudo dkp-pacman -S devkitARM --noconfirm
    - name: Make
      run: |
        source /etc/profile.d/devkit-env.sh
        make -j4
